name: Main

on:
  pull_request:
    branches:
    - main  
  push:
    branches:
    - main
    tags:
    - "*.*.*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Set up Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       profile: minimal
  #       toolchain: stable
    
  #   - name: Test
  #     uses: actions-rs/cargo@v1
  #     with:
  #       command: test

  build:
    name: Release
    needs:
    - lint
    # - test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - aarch64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: ${{ matrix.target }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}
        use-cross: true

    - name: Package
      run: |
        cd target/${{ matrix.target }}/release          
        mv sentry ../../../sentry-${{ matrix.target }}
        cd -

    - name: Create release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: sentry*

  publish:
    name: Publish
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
          
    - name: Publish
      continue-on-error: true
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
